# Generated by Django 5.2.13 on 2026-04-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_rapport', models.CharField(choices=[('QUOTIDIEN', 'Quotidien'), ('ZONES', 'Zones'), ('CLIENTS', 'Clients')], max_length=20)),
                ('format', models.CharField(choices=[('WORD', 'Word'), ('PDF', 'PDF'), ('CSV', 'CSV')], max_length=20)),
                ('fichier', models.FileField(upload_to='reports/')),
                ('date_generation', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fab_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='imports.fabimport')),
            ],
            options={
                'ordering': ['-date_generation', '-created_at'],
            },
        ),
    ]
