# Generated by Django 5.2.13 on 2026-04-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(db_index=True, max_length=120)),
                ('code_centre', models.CharField(db_index=True, max_length=50)),
                ('secteur_facturation', models.CharField(db_index=True, max_length=50)),
                ('tournee_releve', models.CharField(db_index=True, max_length=50)),
                ('nb_clients', models.PositiveIntegerField(default=0)),
                ('solde_total', models.FloatField(default=0)),
                ('solde_moyen', models.FloatField(default=0)),
                ('solde_max', models.FloatField(default=0)),
                ('anciennete_moyenne_jours', models.FloatField(default=0)),
                ('anciennete_max_jours', models.FloatField(default=0)),
                ('score_activite_moyen', models.FloatField(default=0)),
                ('score_solde_total', models.FloatField(default=0)),
                ('score_nb_clients', models.FloatField(default=0)),
                ('score_anciennete_zone', models.FloatField(default=0)),
                ('score_activite_zone', models.FloatField(default=0)),
                ('score_zone', models.FloatField(db_index=True, default=0)),
                ('priorite_zone', models.CharField(choices=[('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('FAIBLE', 'Faible')], db_index=True, default='FAIBLE', max_length=10)),
                ('activite_dominante', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fab_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='imports.fabimport')),
            ],
            options={
                'ordering': ['-score_zone', '-solde_total'],
            },
        ),
    ]
