# Generated by Django 5.2.13 on 2026-04-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_abonnement', models.CharField(db_index=True, max_length=100)),
                ('nom_client', models.CharField(blank=True, default='', max_length=255)),
                ('adresse_client', models.CharField(blank=True, default='', max_length=255)),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('numero_compteur', models.CharField(blank=True, default='', max_length=100)),
                ('code_centre', models.CharField(db_index=True, max_length=50)),
                ('secteur_facturation', models.CharField(db_index=True, max_length=50)),
                ('tournee_releve', models.CharField(db_index=True, max_length=50)),
                ('zone_code', models.CharField(db_index=True, max_length=120)),
                ('activite_client', models.CharField(blank=True, default='', max_length=255)),
                ('famille_activite', models.CharField(blank=True, default='', max_length=100)),
                ('solde', models.FloatField(default=0)),
                ('code_relance', models.IntegerField(default=0)),
                ('date_derniere_facture', models.DateField(blank=True, null=True)),
                ('date_dernier_paiement', models.DateField(blank=True, null=True)),
                ('anciennete_jours', models.IntegerField(default=0)),
                ('anciennete_cappee', models.IntegerField(default=0)),
                ('score_solde', models.FloatField(default=0)),
                ('score_activite', models.FloatField(default=0)),
                ('score_anciennete', models.FloatField(default=0)),
                ('score_client', models.FloatField(db_index=True, default=0)),
                ('priorite_client', models.CharField(choices=[('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('FAIBLE', 'Faible')], db_index=True, default='FAIBLE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fab_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='imports.fabimport')),
            ],
            options={
                'ordering': ['-score_client', '-solde'],
            },
        ),
    ]
