# Generated by Django 5.2.13 on 2026-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier_original', models.FileField(upload_to='fab_uploads/')),
                ('date_import', models.DateTimeField()),
                ('date_fab', models.DateField(blank=True, null=True)),
                ('nombre_lignes_total', models.PositiveIntegerField(default=0)),
                ('nombre_lignes_apres_nettoyage', models.PositiveIntegerField(default=0)),
                ('nombre_clients_filtres', models.PositiveIntegerField(default=0)),
                ('nombre_zones', models.PositiveIntegerField(default=0)),
                ('montant_total', models.FloatField(default=0)),
                ('anciennete_moyenne_jours', models.FloatField(default=0)),
                ('score_moyen_zones', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('SUCCES', 'Succes'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20)),
                ('message_erreur', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_import', '-created_at'],
            },
        ),
    ]
