# Generated by Django 5.2.13 on 2026-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_solde_client', models.FloatField(default=0.55)),
                ('poids_activite_client', models.FloatField(default=0.25)),
                ('poids_anciennete_client', models.FloatField(default=0.2)),
                ('poids_solde_zone', models.FloatField(default=0.5)),
                ('poids_nb_clients_zone', models.FloatField(default=0.25)),
                ('poids_anciennete_zone', models.FloatField(default=0.15)),
                ('poids_activite_zone', models.FloatField(default=0.1)),
                ('cap_anciennete_jours', models.PositiveIntegerField(default=365)),
                ('seuil_haute', models.FloatField(default=70)),
                ('seuil_moyenne', models.FloatField(default=40)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-actif', '-updated_at'],
            },
        ),
    ]
